// Page publique, pas de "use client" nécessaire (aucun hook, contenu
// statique) — même statut que la landing page pour l'auth (jamais wrappée
// dans AuthGuard) mais sans son interactivité (pas de scroll listener ici).
//
// Retour utilisateur : besoin d'un lien "Privacy Policy" pour soumettre la
// demande d'application OAuth Intervals.icu (voir CLAUDE.md, chantier B2 —
// "l'utilisateur doit soumettre une demande sur intervals.icu/oauth/apply").
// Rédigée en anglais délibérément (contrairement au reste de l'UI de
// l'app, en français) : c'est un document de conformité soumis à un
// examinateur externe (Intervals.icu) au sein d'un formulaire lui-même
// entièrement en anglais — pas une page consultée au quotidien par
// l'athlète français. À traduire si besoin plus tard.
//
// Contenu fidèle à l'architecture réelle documentée dans CLAUDE.md (audit
// sécurité, onboarding Intervals.icu, intégrations Strava/Intervals.icu/
// Anthropic/Firebase) — jamais une politique générique copiée-collée.

import Link from 'next/link'
import { LifeCycleMark } from '@/components/layout/lifecycle-mark'
import { ArrowLeft } from 'lucide-react'

export const metadata = {
  title: 'Privacy Policy — LifeCycle Pro',
}

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border/40 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <LifeCycleMark className="w-8 h-8 rounded-[10px]" />
            <span className="text-lg font-bold tracking-tight">LifeCycle <span className="font-light opacity-40">Pro</span></span>
          </Link>
          <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="w-4 h-4" /> Home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16 space-y-10">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-2">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground">Last updated: September 2026</p>
        </div>

        <p className="text-muted-foreground leading-relaxed">
          LifeCycle Pro is a personal training, nutrition, home-management and wellness application.
          It is built and operated by a single individual for personal use; other athletes may use it
          under the same account model. This page explains what data the app handles, where it comes
          from, and how you can control it.
        </p>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">1. What data is collected</h2>
          <ul className="list-disc pl-5 space-y-2 text-muted-foreground leading-relaxed">
            <li><strong className="text-foreground">Account information</strong> — email address and authentication identifiers, via Firebase Authentication (email/password or Google sign-in).</li>
            <li><strong className="text-foreground">Training &amp; wellness data</strong> — activities, fitness metrics (CTL/ATL/TSB, FTP, power curve), sleep, HRV, resting heart rate, and related fields, synced from Intervals.icu once you provide your personal API key or connect via OAuth. This may include data originally sourced from a device manufacturer (e.g. Garmin) when it was itself connected on the Intervals.icu side — LifeCycle Pro never connects directly to Garmin or other device manufacturers; Intervals.icu is always the sole intermediary for that data, per its own terms of service.</li>
            <li><strong className="text-foreground">Manually entered data</strong> — nutrition/recipes, recurring household tasks, plants, injuries, goals, coach memory notes, finance entries, and biometric details (height/age/sex) you choose to enter yourself.</li>
            <li><strong className="text-foreground">AI-generated content</strong> — workout recommendations, training plans, ride/strength-session analyses, and chat messages, generated by sending relevant training context to Anthropic's Claude API.</li>
            <li><strong className="text-foreground">Optional third-party connections</strong> — if you choose to connect Strava, activity data you explicitly export is sent to Strava; if you enable push notifications, a device token is registered with Firebase Cloud Messaging.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">2. How your data is used</h2>
          <p className="text-muted-foreground leading-relaxed">
            Your data is used exclusively to provide the app's own features to you: displaying your
            training/wellness metrics, generating AI coaching content, and running the household/
            nutrition/finance modules you use. It is never sold, rented, or shared with third parties
            for advertising purposes, and the app does not run any advertising or analytics/tracking
            cookies — the only cookie set is a language-preference cookie (`NEXT_LOCALE`).
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">3. Third-party services</h2>
          <p className="text-muted-foreground leading-relaxed">Data may pass through the following services, each governed by its own terms:</p>
          <ul className="list-disc pl-5 space-y-2 text-muted-foreground leading-relaxed">
            <li><strong className="text-foreground">Firebase (Google)</strong> — authentication, database (Firestore) storage, hosting, and optional push notifications. Access to your data is restricted to your own account via Firestore security rules.</li>
            <li><strong className="text-foreground">Intervals.icu</strong> — the source of your synced training/wellness data, connected either via your personal API key or, for automatic activity-analysis notifications, via OAuth.</li>
            <li><strong className="text-foreground">Anthropic (Claude API)</strong> — receives the training/wellness context needed to generate a specific AI response (a workout suggestion, an analysis, a chat reply); handled per Anthropic's own API terms.</li>
            <li><strong className="text-foreground">Strava</strong> — only contacted if you explicitly connect your account and choose to export a strength-training session to it.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">4. Data storage &amp; security</h2>
          <p className="text-muted-foreground leading-relaxed">
            Data is stored in Firestore under a path scoped to your own account, and Firestore
            security rules deny access to any data outside your own path — no other user of the app
            can read or write your data. Data is encrypted in transit (HTTPS/TLS) between your device,
            this app's servers, and the third-party services listed above.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">5. Your rights</h2>
          <p className="text-muted-foreground leading-relaxed">
            From the app's Settings page, you can at any time: <strong className="text-foreground">export</strong> a
            copy of all your stored data, or <strong className="text-foreground">permanently delete</strong> your
            account and every piece of data associated with it, across every module of the app. Deletion is
            immediate and irreversible.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">6. Children</h2>
          <p className="text-muted-foreground leading-relaxed">
            This app is not directed at children and is not knowingly used to collect data from anyone
            under the age of 16.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">7. Changes to this policy</h2>
          <p className="text-muted-foreground leading-relaxed">
            This policy may be updated as the app evolves — for example if a new third-party
            integration is added. The date at the top of this page reflects the last update.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">8. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            Questions about this policy or your data can be sent to{' '}
            <span className="text-foreground font-medium">[contact email to fill in]</span>.
          </p>
        </section>
      </main>
    </div>
  )
}
